version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5430:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'


volumes:
  #  zookeeper_data:
  #    driver: local
  #  kafka_data:
  #    driver: local
  postgres_data:
    driver: local