version: "3"

services:
  proxy-service:
    image: proxy-service:latest
    ports:
      - 8080:8080
    environment:
      - S_POSTGRES_HOST=postgres
      - S_KAFKA_BOOTSTRAP_HOST=kafka:9092
    depends_on:
      - kafka
      - postgres
